version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - app_network
    develop:
      watch:
        - action: sync+restart
          path: ./backend/src
          target: /app

volumes:
  backend:
    driver: local
networks:
  app_network:
    driver: bridge