name: Create Pull Request Feature
on:
  push:
    branches:
      - backend/*
env:
    BRANCH: "backend-main"
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: pull-request
        uses: peter-evans/create-pull-request@v6
        with:
            commit-message: update backend main
            title: "${{ steps.branch-name.outputs.current_branch }} into backend-main"
            body: Credit new contributors by updating AUTHORS
            branch: backend-main
        # uses: repo-sync/pull-request@v2
        # with:
        #   destination_branch: "backend-main"
        #   pr_label: "Feature automated PR (backend/)"
        #   pr_title: "${{ steps.branch-name.outputs.current_branch }} into backend-main"
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   pr_allow_empty: true